jmmourier/laughing-couscous

- .github/workflows/cmake.yml
This PR add github action to automatically build the software repository
> [Software] add automatic build from github actions

- .github/workflows/arduino.yml
- firmware/testMessageParserLibrary/MessageParser
- firmware/testmd25Library/Md25
This PR add the automatic build for the firmware. 
folder with test nad main are build witht the leonardo plateform (compatible with the pro micro we are using)
> [Firmware] Arduino build

- tools/docker/Dockerfile
- tools/docker/docker-compose.yml
- tools/docker/envoy.Dockerfile
- tools/docker/envoy.yml
Add forgotten files from last grpc server PR. This will make grpc web server accessible from a grpc web client
> Add files in order to make grpc server accessible from the client

- firmware/libraries/Md25/Md25.h
- firmware/libraries/MessageParser/CommandData.h
- firmware/main/main.ino
remove debug message, lower timeout, remove useless enum values
> [Firmware] minor fixes

- .gitmodules
- software/CMakeLists.txt
We'll need to write a few tests, using this library will make things easier
> add google test to project

- firmware/libraries/Md25/Md25.cpp
- firmware/libraries/Md25/Md25.h
- firmware/libraries/MessageParser/CommandData.h
- firmware/main/main.ino
- software/modules/hali/src/MessageParser.cpp
make the hardware run !
(following the video on whatsapp)
> Firmware handle commands

- software/application_test_gui/src/CouscousManager.cpp
- software/modules/gui/src/WebPositionService.cpp
- software/modules/gui/web/package-lock.json
- software/modules/gui/web/package.json
- software/modules/gui/web/src/App.css
- software/modules/gui/web/src/App.tsx
- software/modules/gui/web/src/components/StateProvider.tsx
- software/modules/gui/web/src/components/arena/Arena.tsx
- software/modules/gui/web/src/components/arena/PositionIndicator.tsx
- software/modules/gui/web/src/components/arena/Robot.tsx
- software/modules/gui/web/src/hooks/window.ts
- software/modules/gui/web/src/index.tsx
- software/modules/gui/web/src/interfaces/position.ts
- software/modules/gui/web/src/interfaces/size.ts
When running application_test_gui app and the front app we can visualize a simulation of the robot moving in real time using posi and the web server. The position is sent from the back to the front in real time and the front can also set the robot absolute position to posi that will reset it.
> Add arena in front

- .gitmodules
- software/CMakeLists.txt
- software/modules/CMakeLists.txt
- software/modules/gui/CMakeLists.txt
- tools/docker/Dockerfile
remove grpc and boost as submodules. Now grpc is build and installed directly in docker image so compilation is only done during that step. ENABLE_GUI flag as also been removed
> Remove grpc from externals

- software/modules/hali/CMakeLists.txt
- software/modules/hali/include/Serial.h
- software/modules/hali/include/serialib.h
- software/modules/hali/src/Serial.cpp
- software/modules/hali/src/serialib.cpp
This PR remove the boost dependency from hali module
> [Soft][hali] change serial lib to embbeded instead of boost::asio

- software/modules/missi/include/Action.h
- software/modules/missi/include/Missi.h
- software/modules/missi/include/json.hpp
- software/modules/missi/src/Missi.cpp
- software/modules/missi/test/list.json
- software/modules/missi/test/main.cpp
This implement the mission from json file. 
this include using a Json lib, reading the mission from a file and providing the next action to perform as an object "Action".
> [Soft][missi] add json lib and implement mission from file

- software/applications/couscous/src/CouscousManager.cpp
- software/applications/couscous/src/CouscousManager.h
- software/modules/gui/include/IWebServerListener.h
- software/modules/gui/include/WebPositionService.h
- software/modules/gui/src/WebPositionService.cpp
- software/modules/gui/src/protos/robot.proto
- software/modules/gui/web/src/App.tsx
- software/modules/gui/web/src/components/CommunicationProvider.tsx
- software/modules/gui/web/src/components/StateProvider.tsx
- software/modules/gui/web/src/components/arena/Arena.tsx
- software/modules/gui/web/src/components/arena/Robot.tsx
- software/modules/gui/web/src/components/arena/Target.tsx
- can select a target by double click on the front arena
- link front and back via grpc
- provide Interface for webserver listening to targetposition set
> Select pos target on front

- software/modules/gui/web/src/components/arena/Joystick.tsx
- software/modules/gui/web/src/components/arena/PositionIndicator.tsx
- software/modules/gui/web/src/components/arena/Robot.tsx
- software/modules/posi/src/Posi.cpp
- inverse rotation and change 0,0 reference point to bottom left corner on UI front
- add stop button
> [UI/Posi] adapt posi and front

- software/applications/couscous/src/CouscousManager.cpp
- software/applications/couscous/src/CouscousManager.h
- software/applications/couscous/src/main.cpp
- software/modules/hali/CMakeLists.txt
- software/modules/hali/include/HalReal.h
- software/modules/hali/include/HalSimu.h
- software/modules/hali/include/IHali.h
- software/modules/hali/include/IHaliEncodersListener.h
- software/modules/hali/src/HalReal.cpp
- software/modules/hali/src/HalSimu.cpp
- Remove Hali listener
- Couscous app now gets encoders from hali and update posi
> [Hali/Couscous] Remove Hali listener, update couscous

- software/applications/couscous/src/CouscousManager.h
- software/modules/hali/include/HalSimu.h
- software/modules/hali/src/HalSimu.cpp
- software/modules/moti/src/Moti.cpp
This PR fix the speed ratio in hali simu and fix 0 speed value in moti and hali (128 instead of 127)
> Minor fixes  hali simu and moti

- firmware/libraries/Flag/Flag.cpp
- firmware/libraries/Flag/Flag.h
- firmware/libraries/GameTimer/GameTimer.cpp
- firmware/libraries/GameTimer/GameTimer.h
- firmware/libraries/Leds/Leds.cpp
- firmware/libraries/Leds/Leds.h
- firmware/libraries/Srf02/Srf02.cpp
- firmware/libraries/Srf02/Srf02.h
- firmware/libraries/Switches/Switches.cpp
- firmware/libraries/Switches/Switches.h
- firmware/main/Flag
- firmware/main/GameTimer
- firmware/main/Leds
- firmware/main/Srf02
- firmware/main/Switches
- firmware/main/main.ino
- firmware/testMessageParserLibrary/testMessageParserLibrary.ino
- firmware/testRoutine/Flag
- firmware/testRoutine/GameTimer
- firmware/testRoutine/Grabber
- firmware/testRoutine/Leds
- firmware/testRoutine/Md25
- firmware/testRoutine/Switches
- firmware/testRoutine/testRoutine.ino
- software/modules/hali/include/HalReal.h
- software/modules/hali/include/HalSimu.h
- software/modules/hali/include/IHali.h
- software/modules/hali/src/HalReal.cpp
- software/modules/hali/src/HalSimu.cpp
- software/modules/hali/test/main.cpp
This PR update firmware and hali according to hardware updated
- re-wiring
- flag that rise after 95s
- switch to select color
- Led for debug info
- Timer to stop the game
- start button
- distance sensor
> Update firmware with new hardware

- software/modules/gui/web/src/components/arena/Arena.tsx
- software/modules/gui/web/src/components/arena/Target.tsx
- software/modules/posi/include/Posi.h
- software/modules/posi/src/Posi.cpp
- software/modules/posi/test/PosiTest.cpp
- software/modules/utils/include/constant.h
Posi orientation now can only be between 0 and < 6.28318531 (perimeter)
> [posi] fix position to absolute between 0 and 2 * PI

- software/applications/couscous/src/CouscousManager.cpp
- software/applications/couscous/src/CouscousManager.h
- software/modules/gui/include/IWebServerRequestListener.h
- software/modules/gui/include/WebPositionService.h
- software/modules/gui/src/WebPositionService.cpp
- software/modules/gui/src/protos/robot.proto
- software/modules/gui/web/src/App.tsx
- software/modules/gui/web/src/components/CommunicationProvider.tsx
- software/modules/gui/web/src/components/arena/Joystick.tsx
- software/modules/gui/web/src/components/arena/PositionIndicator.tsx
- software/modules/navi/include/Navi.h
- software/modules/navi/src/Navi.cpp
- New button on front to select and send orientation
- Add request orientation trigger to webServer
- send orientation request no navi module through couscous app
> Send orientation from front

- software/applications/couscous/CMakeLists.txt
- software/applications/couscous/mission.json
- software/applications/couscous/src/CouscousManager.cpp
- software/applications/couscous/src/CouscousManager.h
- software/applications/couscous/src/main.cpp
- software/modules/missi/CMakeLists.txt
- software/modules/missi/include/Action.h
- software/modules/missi/include/Missi.h
- software/modules/missi/src/Missi.cpp
- software/modules/missi/test/list.json
- software/modules/missi/test/main.cpp
- software/modules/missi/test/testTimeout.cpp
- software/modules/navi/src/Navi.cpp
to test copy the file mission.json in the same folder as the couscous app
> Use missi in couscous

- software/modules/missi/src/Missi.cpp
- tools/ansible/playbook/roles/push_back/tasks/main.yml
- tools/ansible/playbook/roles/setup_env/templates/couscous_app.service.j2
- tools/ansible/playbook/run.yml
- tools/docker/docker-compose.yml
- add new MISSION_PATH env variable to target mission.json file in order to have two different values dev/prod
- ansible: mission.json is now pushed when building back and push
> Ansible copy mission json

- tools/ansible/playbook/roles/push_back/tasks/main.yml
- tools/ansible/playbook/roles/run/tasks/main.yml
- tools/ansible/playbook/roles/setup_pi/tasks/main.yml
- tools/docker/docker-compose.yml
> Fix ansible

- software/applications/couscous/src/CouscousManager.cpp
- software/applications/couscous/src/CouscousManager.h
- software/modules/gui/include/WebPositionService.h
- software/modules/gui/include/WebServer.h
- software/modules/gui/src/WebPositionService.cpp
- software/modules/gui/src/WebServer.cpp
- software/modules/gui/src/protos/robot.proto
- software/modules/gui/web/src/App.tsx
- software/modules/gui/web/src/components/CommunicationProvider.tsx
- software/modules/gui/web/src/components/StateProvider.tsx
- software/modules/gui/web/src/components/arena/Arena.tsx
- software/modules/gui/web/src/components/arena/Robot.tsx
- add battery info on front
- link battery from hali (get battery) ---> couscous app (fetch and send to front) ---> grpc to front
> Add battery on front
